schema = 3

[mod]
  [mod."codeberg.org/readeck/go-readability/v2"]
    version = "v2.1.1"
    hash = "sha256-g0JCqWYRtdJUkBdCjGe33gr1Q51QYUvQtXv4U4slQ7I="
  [mod."github.com/JohannesKaufmann/dom"]
    version = "v0.2.0"
    hash = "sha256-vrJG0spzGYAflEvAz0sYvD6nC6IYI5lAZbIx82GBtQE="
  [mod."github.com/JohannesKaufmann/html-to-markdown/v2"]
    version = "v2.3.3"
    hash = "sha256-B+ZJk86VJUscaf91tv5uuTeL6u9HN6cS+5+4TOiNC+E="
  [mod."github.com/andybalholm/cascadia"]
    version = "v1.3.3"
    hash = "sha256-jv7ZshpSd7FZzKKN6hqlUgiR8C3y85zNIS/hq7g76Ho="
  [mod."github.com/araddon/dateparse"]
    version = "v0.0.0-20210429162001-6b43995a97de"
    hash = "sha256-UuX84naeRGMsFOgIgRoBHG5sNy1CzBkWPKmd6VbLwFw="
  [mod."github.com/bytedance/sonic"]
    version = "v1.13.2"
    hash = "sha256-IF2qmt4IxTwivMWHUJC8sg6d85/ORb2SWvJ54fvoAMI="
  [mod."github.com/bytedance/sonic/loader"]
    version = "v0.2.4"
    hash = "sha256-rv9LnePpm4OspSVbfSoVbohXzhu+dxE1BH1gm3mTmTc="
  [mod."github.com/cloudwego/base64x"]
    version = "v0.1.5"
    hash = "sha256-MyUYTveN48DhnL8mwAgCRuMExLct98uzSPsmYlfaa4I="
  [mod."github.com/gabriel-vasile/mimetype"]
    version = "v1.4.8"
    hash = "sha256-ElqfQtnoGHyVqtN0mJjeWakQ6N5x+nVaX3+uOV7Q5Xk="
  [mod."github.com/gin-contrib/cors"]
    version = "v1.7.5"
    hash = "sha256-qVe2+F8fGBJ5uj05Ehzt20xHkV/s6C+xWeQChktzaMw="
  [mod."github.com/gin-contrib/sse"]
    version = "v1.0.0"
    hash = "sha256-xnaabOxDN+ojnHQC7mHd/876Z9nWFScW+JrMm1HWREw="
  [mod."github.com/gin-gonic/gin"]
    version = "v1.10.1"
    hash = "sha256-D98+chAdjb6JcLPkscOr8TgTW87UqA4h3cnY0XIr16c="
  [mod."github.com/go-playground/locales"]
    version = "v0.14.1"
    hash = "sha256-BMJGAexq96waZn60DJXZfByRHb8zA/JP/i6f/YrW9oQ="
  [mod."github.com/go-playground/universal-translator"]
    version = "v0.18.1"
    hash = "sha256-2/B2qP51zfiY+k8G0w0D03KXUc7XpWj6wKY7NjNP/9E="
  [mod."github.com/go-playground/validator/v10"]
    version = "v10.26.0"
    hash = "sha256-/jMKICp8LTcJVt+b4YRTnJM84r7HK6aT0oqO7Q8SRs8="
  [mod."github.com/go-shiori/dom"]
    version = "v0.0.0-20230515143342-73569d674e1c"
    hash = "sha256-4lm9KZfR2XnfZU9KTG+4jqLYZqbfL74AMO4y3dKpIbg="
  [mod."github.com/goccy/go-json"]
    version = "v0.10.5"
    hash = "sha256-/EtlGihP0/7oInzMC5E0InZ4b5Ad3s4xOpqotloi3xw="
  [mod."github.com/gogs/chardet"]
    version = "v0.0.0-20211120154057-b7413eaefb8f"
    hash = "sha256-4MeqBJsh4U+ZEbfdDwdciTYMlQWkCil2KJbUxHjBSIo="
  [mod."github.com/json-iterator/go"]
    version = "v1.1.12"
    hash = "sha256-To8A0h+lbfZ/6zM+2PpRpY3+L6725OPC66lffq6fUoM="
  [mod."github.com/klauspost/cpuid/v2"]
    version = "v2.2.10"
    hash = "sha256-o21Tk5sD7WhhLUoqSkymnjLbzxl0mDJCTC1ApfZJrC0="
  [mod."github.com/kr/text"]
    version = "v0.2.0"
    hash = "sha256-fadcWxZOORv44oak3jTxm6YcITcFxdGt4bpn869HxUE="
  [mod."github.com/leodido/go-urn"]
    version = "v1.4.0"
    hash = "sha256-Q6kplWkY37Tzy6GOme3Wut40jFK4Izun+ij/BJvcEu0="
  [mod."github.com/mattn/go-isatty"]
    version = "v0.0.20"
    hash = "sha256-qhw9hWtU5wnyFyuMbKx+7RB8ckQaFQ8D+8GKPkN3HHQ="
  [mod."github.com/modern-go/concurrent"]
    version = "v0.0.0-20180306012644-bacd9c7ef1dd"
    hash = "sha256-OTySieAgPWR4oJnlohaFTeK1tRaVp/b0d1rYY8xKMzo="
  [mod."github.com/modern-go/reflect2"]
    version = "v1.0.2"
    hash = "sha256-+W9EIW7okXIXjWEgOaMh58eLvBZ7OshW2EhaIpNLSBU="
  [mod."github.com/pelletier/go-toml/v2"]
    version = "v2.2.3"
    hash = "sha256-fE++SVgnCGdnFZoROHWuYjIR7ENl7k9KKxQrRTquv/o="
  [mod."github.com/twitchyliquid64/golang-asm"]
    version = "v0.15.1"
    hash = "sha256-HLk6oUe7EoITrNvP0y8D6BtIgIcmDZYtb/xl/dufIoY="
  [mod."github.com/ugorji/go/codec"]
    version = "v1.2.12"
    hash = "sha256-sp1LJ93UK7mFwgZqG8jxCgTCPgKR74HNU6XxX0Jfjm0="
  [mod."golang.org/x/arch"]
    version = "v0.15.0"
    hash = "sha256-EsCsTDmn+j3S8yzV4n2WJyDuYBDwIlj29M9OBxWNMGQ="
  [mod."golang.org/x/crypto"]
    version = "v0.39.0"
    hash = "sha256-FtwjbVoAhZkx7F2hmzi9Y0J87CVVhWcrZzun+zWQLzc="
  [mod."golang.org/x/net"]
    version = "v0.41.0"
    hash = "sha256-6/pi8rNmGvBFzkJQXkXkMfL1Bjydhg3BgAMYDyQ/Uvg="
  [mod."golang.org/x/sys"]
    version = "v0.33.0"
    hash = "sha256-wlOzIOUgAiGAtdzhW/KPl/yUVSH/lvFZfs5XOuJ9LOQ="
  [mod."golang.org/x/text"]
    version = "v0.26.0"
    hash = "sha256-N+27nBCyGvje0yCTlUzZoVZ0LRxx4AJ+eBlrFQVRlFQ="
  [mod."google.golang.org/protobuf"]
    version = "v1.36.6"
    hash = "sha256-lT5qnefI5FDJnowz9PEkAGylH3+fE+A3DJDkAyy9RMc="
  [mod."gopkg.in/yaml.v3"]
    version = "v3.0.1"
    hash = "sha256-FqL9TKYJ0XkNwJFnq9j0VvJ5ZUU1RvH/52h/f5bkYAU="
